//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjectStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public string L_ID { get; set; }
        public string L_name { get; set; }
        public string L_fullname { get; set; }
        public string L_department { get; set; }
        public string L_gender { get; set; }
        public Nullable<System.DateTime> L_birthday { get; set; }
        public string L_phone { get; set; }
        public string L_email { get; set; }
    }
}
