//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjectStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int Pro_ID { get; set; }
        public string Progress1 { get; set; }
        public string Progress2 { get; set; }
        public string Progress3 { get; set; }
        public string Progress4 { get; set; }
        public string LinkSource { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
