//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjectStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectManagements = new HashSet<ProjectManagement>();
        }
    
        public int P_ID { get; set; }
        public string P_title { get; set; }
        public string P_description { get; set; }
        public Nullable<System.DateTime> P_fromtime { get; set; }
        public Nullable<System.DateTime> P_totime { get; set; }
        public string P_point { get; set; }
        public string L_ID { get; set; }
    
        public virtual Lecture Lecture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.ComponentModel.Browsable(false)]
        public virtual ICollection<ProjectManagement> ProjectManagements { get; set; }
    }
}
