//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjectStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int P_ID { get; set; }
        public string P_title { get; set; }
        public string P_description { get; set; }
        public Nullable<System.DateTime> P_fromtime { get; set; }
        public Nullable<System.DateTime> P_totime { get; set; }
        public string P_point { get; set; }
    
        public virtual Progress Progress { get; set; }
    }
}
